In [1]:
import numpy as np

In [4]:
X = np.array([[1,3],[4,6]])
print X

[[1 3]
 [4 6]]


In [15]:
X.astype(float)/X.sum(axis = 1,keepdims = True)

array([[ 0.25,  0.75],
       [ 0.4 ,  0.6 ]])

In [10]:
X.astype(float)

array([[ 1.,  3.],
       [ 4.,  6.]])