In [1]:
import numpy as np

In [4]:
X = np.array([[1,3],[4,6]])
print X

[[1 3]
 [4 6]]


In [15]:
X.astype(float)/X.sum(axis = 1,keepdims = True)

array([[ 0.25,  0.75],
       [ 0.4 ,  0.6 ]])

In [10]:
X.astype(float)

array([[ 1.,  3.],
       [ 4.,  6.]])

In [14]:
from itertools import product
possible_events = [-1, 0, 1, 3, 4, 6, 7, 8, 104, 100]
events_dict = {}
for i in product(possible_events,repeat=3):
    events_dict[i] = 0

In [8]:
import numpy as np
a = np.array([1,2,3])

In [11]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [13]:
for i in range(1):
    print i

0


In [18]:
a[:2]

array([1, 2])

In [28]:
c = np.array([[3,1,2],[0,2,2],[5,5,5]])
d = np.array([0,1,0])

In [33]:
d*c.T

array([[0, 0, 0],
       [1, 2, 5],
       [0, 0, 0]])

In [30]:
c

array([[3, 1, 2],
       [0, 2, 2],
       [5, 5, 5]])

In [43]:
idx = c.argmax(axis = None)
multi_idx = np.unravel_index(idx, c.shape)

In [44]:
multi_idx

(2, 0)

In [45]:
events_row_map = {
            -1 : 7
            ,1 : 0
            ,3 : 1
            ,4 : 2
            ,6 : 5
            ,7 : 6
            ,8 : 3
            ,104 : 4
        }

In [49]:
[key for key, value in events_row_map.items() if value == 4][0]

104

In [50]:
A = np.array([[.5,.25,.25],[.5,0,.5],[.25,.25,.5]])

In [58]:
A*A

array([[ 0.25  ,  0.0625,  0.0625],
       [ 0.25  ,  0.    ,  0.25  ],
       [ 0.0625,  0.0625,  0.25  ]])

In [57]:
from numpy import linalg as LA
LA.matrix_power(A,2)

array([[ 0.4375,  0.1875,  0.375 ],
       [ 0.375 ,  0.25  ,  0.375 ],
       [ 0.375 ,  0.1875,  0.4375]])

In [2]:
for i in range(1):
    print i

0


In [ ]:
col = 'X'
'X' = np.zeros

In [10]:
from urlparse import urlparse
a = urlparse('')

In [24]:
import numpy as np
import pandas as pd
a = np.array([['a','f'],['c','d'],['a','b']])
a_df = pd.DataFrame(a, columns = ['first','second'])

In [25]:
a_df

first second
0     a      f
1     c      d
2     a      b

In [26]:
a_df['num'] = np.array([2,1,3])
a_df

first second  num
0     a      f    2
1     c      d    1
2     a      b    3

In [29]:
a_df.sort_values(['num','first','second'])

first second  num
1     c      d    1
0     a      f    2
2     a      b    3

In [15]:
a_df['third'] = a_df['first']+a_df['second']

In [16]:
a_df['third']

0    ab
1    cd
2    ef
Name: third, dtype: object

In [17]:
a_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
first     3 non-null object
second    3 non-null object
third     3 non-null object
dtypes: object(3)
memory usage: 144.0+ bytes


In [18]:
for i in range(a_df.shape[0]):
    print i

0
1
2


In [1]:
import platform
platform.architecture()

('64bit', 'ELF')

In [2]:
import numpy as np
import pandas as pd
a = np.array([['a','c']])
a_df = pd.DataFrame(a, columns = ['first','second'])

In [3]:
a_df

first second
0     a      c

In [6]:
a_df['third'] = 0.0

In [7]:
a_df

first second  third
0     a      c    0.0